# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml"
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
# Forge for 1.14.4 is version 28
loaderVersion="[28,)"
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/Pyrofab/SpawnerControl/issues"
# If the mods defined in this file should show as seperate resource packs
showAsResourcePack=false

[[mods]]
  modId="spawnercontrol"
  version="${file.jarVersion}"
  displayName="Spawner Control"
#  updateJSONURL="minecraftforge.net/versions.json"
  displayURL="www.curseforge.com/minecraft/mc-mods/mob-spawner-control"
  logoFile="logo.png"
  credits="Logo by DoctoRat."
  authors=["Pyrofab", "Laike-Endaril"]
  description='''
  This mod provides ways to configure mob spawners, to discourage their use in mob farms or to incentivize players to seek and destroy them.
  It can be used on a forge server with vanilla clients, though you should refrain from using the custom spawners feature when doing so.
  '''

  [[dependencies.spawnercontrol]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"

  [[dependencies.spawnercontrol]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15,)"
    ordering="NONE"
    side="BOTH"